# Generated by Django 3.0.5 on 2020-07-21 14:18

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_referral_answer_attachment_with_base_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralUrgency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        help_text="Expected treatment duration", verbose_name="duration"
                    ),
                ),
                (
                    "requires_justification",
                    models.BooleanField(
                        help_text="Whether to require a justification when this urgency is selected",
                        verbose_name="requires justification",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral urgency",
                "db_table": "partaj_referral_urgency",
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.AddField(
            model_name="referral",
            name="urgency_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Urgency level. When is the referral answer needed?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.ReferralUrgency",
                verbose_name="urgency",
            ),
        ),
        migrations.CreateModel(
            name="ReferralUrgencyTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.ReferralUrgency",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral urgency translation",
                "db_table": "partaj_referral_urgency_translation",
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModel, models.Model),
        ),
    ]
